# Generated by Django 4.2.14 on 2024-07-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contact_num', models.IntegerField()),
                ('email_sub', models.CharField(max_length=255)),
                ('email_msg', models.TextField(max_length=255)),
            ],
        ),
    ]
